CREATE VIEW VIEW_USER_INFORMATION AS
	SELECT USERS.USER_ID, USERS.FIRST_NAME, USERS.LAST_NAME, USERS.YEAR_OF_BIRTH, USERS.MONTH_OF_BIRTH, USERS.DAY_OF_BIRTH, USERS.GENDER, C_CURRENT.CITY_NAME, C_CURRENT.STATE_NAME, C_CURRENT.COUNTRY_NAME, C_HOMETOWN.CITY_NAME, C_HOMETOWN.STATE_NAME, C_HOMETOWN.COUNTRY_NAME, PROGRAMS.INSTITUTION, EDUCATION.PROGRAM_YEAR, PROGRAMS.CONCENTRATION, PROGRAMS.DEGREE
	FROM USERS
	LEFT JOIN USERS_CURRENT_CITIES ON USERS.USER_ID=USERS_CURRENT_CITIES.USER_ID
	LEFT JOIN CITIES C_CURRENT ON USERS_CURRENT_CITIES.CURRENT_CITY_ID=C_CURRENT.CITY_ID
	LEFT JOIN USERS_HOMETOWN_CITIES ON USERS.USER_ID=USERS_HOMETOWN_CITIES.USER_ID
	LEFT JOIN CITIES C_HOMETOWN ON USERS_HOMETOWN_CITIES.HOMETOWN_CITY_ID=C_HOMETOWN.CITY_ID 
	LEFT JOIN EDUCATION ON USERS.USER_ID=EDUCATION.USER_ID
	LEFT JOIN PROGRAMS ON EDUCATION.PROGRAM_ID=PROGRAMS.PROGRAM_ID


CREATE VIEW VIEW_ARE_FRIENDS AS
	SELECT USER1_ID, USER2_ID
	FROM FRIENDS

CREATE VIEW VIEW_PHOTO_INFORMATION AS
	SELECT PHOTOS.ALBUM_ID, ALBUMS.OWNER_ID, ALBUMS.COVER_PHOTO_ID, ALBUMS.ALBUM_NAME, ALBUMS.ALBUM_CREATED_TIME, ALBUMS.ALBUM_MODIFIED_TIME, ALBUMS.ALBUM_LINK, ALBUMS.ALBUM_VISIBILITY, PHOTOS.PHOTO_ID,PHOTOS.PHOTO_CAPTION, PHOTOS.PHOTO_CREATED_TIME, PHOTOS.PHOTO_MODIFIED_TIME, PHOTOS.PHOTO_LINK
	FROM PHOTOS
	LEFT JOIN ALBUMS ON PHOTOS.ALBUM_ID=ALBUMS.ALBUM_ID

CREATE VIEW VIEW_EVENT_INFORMATION AS
	SELECT USER_EVENTS.EVENT_ID, USER_EVENTS.EVENT_CREATOR_ID, USER_EVENTS.EVENT_NAME, USER_EVENTS.EVENT_TAGLINE, USER_EVENTS.EVENT_DESCRIPTION, USER_EVENTS.EVENT_HOST, USER_EVENTS.EVET_TYPE, USER_EVENTS.EVENT_SUBTYPE, USER_EVENTS.EVETN_ADDRESS, CITIES.CITY_NAME, CITIES.STATE_NAME, CITIES.COUNTRY_NAME, USER_EVENTS.EVENT_START_TIME, USER_EVENTS.EVENT_END_TIME
	FROM USER_EVETNS
	LEFT JOIN CITIES ON USER_EVENTS.EVENT_CITY_ID=CITIES.CITY_ID

CREATE VIEW VIEW_TAG_INFORMATION AS
	SELECT TAG_PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X_, TAG_Y
	FROM TAGS